name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Waiting for Vercel deployment
        uses: mskelton/wait-for-vercel-action@v1
        id: wait-for-vercel
        with:
          prod-url: bull-six.vercel.app
          token: ${{ secrets.VERCEL_TOKEN }}
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: |
            ${{ steps.wait-for-vercel.outputs.url }}
          budgetPath: budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
